<template>
  <div class="login">
    <van-list :finished="finished"
              finished-text="没有更多了"
              @load="onLoad">
      <van-cell v-for="(item,index) in dataList"
                :key="index">
        <van-card @click="handleClick(item)"
                  :desc="item.house"
                  :title="item.realname"
                  :thumb="item.headimgurl">
          <template #tags
                    class="m-t-20">
            <van-tag plain
                     type="danger"
                     class="m-r-20">{{item.age}}岁</van-tag>
            <van-tag plain
                     class="m-r-20"
                     type="danger">
              {{item.education}}</van-tag>
            <van-tag plain
                     class="m-r-20"
                     type="danger">
              {{item.profession}}</van-tag>
            <van-tag plain
                     class="m-r-20"
                     type="danger">
              {{item.income}}</van-tag>
            <div class="m-t-20 main">
              择偶标准：{{item.monologue?item.monologue:'暂无'}}
            </div>
          </template>
          <template #footer>
            <van-button size="mini">获取微信</van-button>
          </template>
        </van-card>
      </van-cell>
    </van-list>
  </div>
</template>
<script>
import { setRem } from '@/utils'
export default {
  name: 'login',
  data() {
    return {
      loading: false,
      finished: false,
      dataList: [
        {
          id: 211254,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '金水区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/b9qpTKJ4HuwgrZpIBzXZPdtEpBYgjIuibniadxU02t5ibAv5pXTAMCgeEN19q3GJPJ5emQg6gmYllwMQ7HgTFxM9w/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6j1e8Mhbf-on8meAU7iXwiY.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6j1e8Mhbf-on8meAU7iXwiY.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6j1e8Mhbf-on8meAU7iXwiY.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '企业高管',
          house: '有房-有车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '63kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '五年内结婚',
          create_time: 1636198244,
          update_time: null,
          rec_time: 1645403974,
          birthday: '1998-06-19',
          work_data: '河南省,郑州市,金水区',
          height: '173cm',
          income: '8K-12K',
          education: '本科',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,郑州市,金水区',
          age: 23,
          tousu: 0,
          realname: '李曹曼',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 55,
          mincouple_age: 18,
          couple_marriage: null,
          status: '1',
          show_counts: 4,
          action_conuts: 39,
          external_get: 9,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 211253,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '二七区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJBuRu5ljGOQoZTZN0tjlJ4hwQoboTTrDAhkM6dEw1XfibboHDmHfvoaasRuBqALAHXrEwDkFLWpxg/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6l9wI6mSrQL1wC5TDn-E_Ng.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6l9wI6mSrQL1wC5TDn-E_Ng.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6l9wI6mSrQL1wC5TDn-E_Ng.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '公务员',
          house: '有房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '49kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '两年内结婚',
          create_time: 1636198356,
          update_time: null,
          rec_time: 1645403891,
          birthday: '1994-05-26',
          work_data: '河南省,郑州市,二七区',
          height: '163cm',
          income: '5K-8K',
          education: '本科',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,南阳市,社旗县',
          age: 28,
          tousu: 0,
          realname: '小鹿',
          mobile: '',
          uname: '',
          vip_start: 0,
          vip_end: 0,
          vip: 0,
          maxcouple_age: 55,
          mincouple_age: 18,
          couple_marriage: null,
          status: '1',
          show_counts: 2,
          action_conuts: 24,
          external_get: 20,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 211220,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '惠济区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/HDAWaCzSXlsPHfOg3Hfn7iapo1vuJ2SrnCRyHbFMEnsm9JrjRz9570VydME5viaJic5lhQWcwbMCP5AIqPPWP98PQ/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6pncPX6ckhb1F10WEYksjDM.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6pncPX6ckhb1F10WEYksjDM.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6pncPX6ckhb1F10WEYksjDM.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '销售/市场',
          house: '有房-有车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '49kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '一年内结婚',
          create_time: 1636169848,
          update_time: null,
          rec_time: 1645403832,
          birthday: '1991-10-22',
          work_data: '河南省,郑州市,惠济区',
          height: '162cm',
          income: '12K-20K',
          education: '本科',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,商丘市,其它区',
          age: 31,
          tousu: 0,
          realname: '周娅',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 55,
          mincouple_age: 18,
          couple_marriage: null,
          status: '1',
          show_counts: 1,
          action_conuts: 13,
          external_get: 13,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 211156,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '管城回族区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLpSwG8Qg23TbKz9f66EQhH3lI6sze5T9IAZbRL67OicPnMo1pGkT9jdibs9IjOE3Y7ENSujKaXPS0g/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6sl9DktOjUisMbWVr51F3U0.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6sl9DktOjUisMbWVr51F3U0.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6sl9DktOjUisMbWVr51F3U0.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '电商',
          house: '有房-有车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '50kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '一年内结婚',
          create_time: 1641184823,
          update_time: null,
          rec_time: 1645403769,
          birthday: '1988-04-19',
          work_data: '河南省,郑州市,管城回族区',
          height: '165cm',
          income: '5K-8K',
          education: '大专',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,郑州市,中牟县',
          age: 33,
          tousu: 0,
          realname: '孟金萍',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 37,
          mincouple_age: 34,
          couple_marriage: '未婚',
          status: '1',
          show_counts: 2,
          action_conuts: 13,
          external_get: 16,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 213089,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '管城回族区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTIZyicJ77q14vz8fxNt9hgGG6I0Xibt7RaATp0ZT0h69XYXYctf5R3RNaibTMMDIJk9icLuHe94cNgiaSg/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6jhpuKtfMp8FiFDLGGIGQTM.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6jhpuKtfMp8FiFDLGGIGQTM.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6jhpuKtfMp8FiFDLGGIGQTM.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '医护人员',
          house: '有房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '55kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '一年内结婚',
          create_time: 1644117436,
          update_time: null,
          rec_time: 1645326637,
          birthday: '1987-03-27',
          work_data: '河南省,郑州市,管城回族区',
          height: '162cm',
          income: '5K-8K',
          education: '本科',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,安阳市,内黄县',
          age: 34,
          tousu: 0,
          realname: '张现利',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 38,
          mincouple_age: 31,
          couple_marriage: '未婚',
          status: '1',
          show_counts: 1,
          action_conuts: 41,
          external_get: 5,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 213363,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '金水区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJ3lpbBhawChfWT5WlI9zxGrVO7qkYHQfzmfmHgN31EmzdVpAhHIibAh5hdZicavE4BN1WG37ymBZAw/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6p6PpD1rDil1x0Rn2vMXwNk.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6p6PpD1rDil1x0Rn2vMXwNk.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '三观一致，能好好沟通，不冷暴力，对家庭有责任感',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6p6PpD1rDil1x0Rn2vMXwNk.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '教师',
          house: '无房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '50kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '一年内结婚',
          create_time: 1645325680,
          update_time: null,
          rec_time: 1645326518,
          birthday: '1988-12-18',
          work_data: '河南省,郑州市,金水区',
          height: '163cm',
          income: '5K-8K',
          education: '研究生',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,南阳市,社旗县',
          age: 33,
          tousu: 0,
          realname: '柏杨',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 55,
          mincouple_age: 18,
          couple_marriage: null,
          status: '1',
          show_counts: 1,
          action_conuts: 70,
          external_get: 4,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 206530,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '管城回族区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKibqX2nPhYJDZBIRNWpKpFstnoEhkz5HhvFWsvLjNTj6NzJicpus82bRf9jaIP8fRvxficpicFzYsGdQ/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6kQesXW7CMNCQDWmTZVzhVk.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6kQesXW7CMNCQDWmTZVzhVk.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6kQesXW7CMNCQDWmTZVzhVk.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '教练',
          house: '无房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '60kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '一年内结婚',
          create_time: 1645273689,
          update_time: null,
          rec_time: 1645326437,
          birthday: '1991-09-02',
          work_data: '河南省,郑州市,管城回族区',
          height: '165cm',
          income: '8K-12K',
          education: '大专',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,郑州市,管城回族区',
          age: 30,
          tousu: 0,
          realname: '曹娅婧',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 55,
          mincouple_age: 18,
          couple_marriage: null,
          status: '1',
          show_counts: 1,
          action_conuts: 66,
          external_get: 2,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 203967,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '管城回族区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/z5c0Fsf8CIVQbfU1WJXMHTnxRozAdOHNZqetaYYI815wjJHWBPHly2Ncy4fHwzkaCJYcAIpelaIjoXpyPax8YQ/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6uC1HX8tEghJ9jbY2SCV-gw.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6uC1HX8tEghJ9jbY2SCV-gw.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '………………',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6uC1HX8tEghJ9jbY2SCV-gw.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '教师',
          house: '无房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '80kg',
          bodily: null,
          smoke: '偶尔抽烟喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '两年内结婚',
          create_time: 1645242247,
          update_time: null,
          rec_time: 1645326376,
          birthday: '1998-04-16',
          work_data: '河南省,郑州市,管城回族区',
          height: '170cm',
          income: '3K-5K',
          education: '中专',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,驻马店市,驿城区',
          age: 23,
          tousu: 0,
          realname: '李慧',
          mobile: '',
          uname: '',
          vip_start: 0,
          vip_end: 0,
          vip: 0,
          maxcouple_age: 23,
          mincouple_age: 20,
          couple_marriage: null,
          status: '1',
          show_counts: 1,
          action_conuts: 85,
          external_get: 15,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 211071,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '中原区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/3hUrCXAxDEiac8mG8xiakpNtUsug4smu9WJibztNfZcZiaTsZZpuw3ngVlCicx4fuicyoGa17DuibcJT7VbQNiaBNyHiaTQ/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6lCP4w4hSPH8wEnFzlSHDZQ.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6lCP4w4hSPH8wEnFzlSHDZQ.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '倾心一人。',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6lCP4w4hSPH8wEnFzlSHDZQ.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '自由职业',
          house: '无房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '55kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '暂无打算结婚',
          create_time: 1636029263,
          update_time: null,
          rec_time: 1645237471,
          birthday: '1995-02-10',
          work_data: '河南省,郑州市,中原区',
          height: '168cm',
          income: '8K-12K',
          education: '大专',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,郑州市,中原区',
          age: 27,
          tousu: 0,
          realname: '李佳',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 55,
          mincouple_age: 18,
          couple_marriage: null,
          status: '1',
          show_counts: 1,
          action_conuts: 57,
          external_get: 9,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 211044,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '郑东新区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/M6q3PbFA9sdmRibd0lqySTJwbbZjbB3gfnYDQMLV7G6e5K4icJvbsf4vHI6qkhwcgOvniadZqrVhmqfiakdPoJAyhA/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6lgJFWH78Az9JRh15agGmQ8.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6lgJFWH78Az9JRh15agGmQ8.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6lgJFWH78Az9JRh15agGmQ8.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '教师',
          house: '无房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '55kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '三年内结婚',
          create_time: 1638761968,
          update_time: null,
          rec_time: 1645237298,
          birthday: '1998-09-12',
          work_data: '河南省,郑州市,郑东新区',
          height: '166cm',
          income: '5K-8K',
          education: '本科',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,濮阳市,华龙区',
          age: 24,
          tousu: 1,
          realname: '陈然然',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 55,
          mincouple_age: 18,
          couple_marriage: null,
          status: '1',
          show_counts: 2,
          action_conuts: 131,
          external_get: 25,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 204747,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '其它区',
          city: '开封市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/8AltZyhRCsqEKB1lsxfBnubt2NIhIU7Y2cQr7Iux7pBxK5pwFS2uNicMvmHr1m4jABELEIeMhiaN3icZ8SI0tyZdA/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6u78ywgAiWU_E1UxStqt_1o.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6u78ywgAiWU_E1UxStqt_1o.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6u78ywgAiWU_E1UxStqt_1o.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '教师',
          house: '无房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '49kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '两年内结婚',
          create_time: 1645232147,
          update_time: null,
          rec_time: 1645237175,
          birthday: '1996-06-19',
          work_data: '河南省,开封市,其它区',
          height: '160cm',
          income: '3K-5K',
          education: '本科',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,开封市,鼓楼区',
          age: 25,
          tousu: 0,
          realname: '林宁',
          mobile: '',
          uname: '',
          vip_start: 0,
          vip_end: 0,
          vip: 0,
          maxcouple_age: 28,
          mincouple_age: 23,
          couple_marriage: '未婚',
          status: '1',
          show_counts: 2,
          action_conuts: 104,
          external_get: 69,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 212037,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '金水区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/62uTqibdQITSMMohwuYXeBynkWqvoU7oeTxPbUH9j5IoIyiaRKHrUcuibws44D95REa9Tslniay47gx5yIcaybfzDQ/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6gjH0LgI69B0eCW6RYsyTfw.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6gjH0LgI69B0eCW6RYsyTfw.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '性格阳光开朗，幽默，有上进心，有责任心，孝顺，三观合',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6gjH0LgI69B0eCW6RYsyTfw.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '财务',
          house: '无房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '53kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '三年内结婚',
          create_time: 1645194607,
          update_time: null,
          rec_time: 1645237081,
          birthday: '1996-01-30',
          work_data: '河南省,郑州市,金水区',
          height: '165cm',
          income: '5K-8K',
          education: '本科',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,平顶山市,叶县',
          age: 26,
          tousu: 0,
          realname: '田美玲',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 55,
          mincouple_age: 18,
          couple_marriage: null,
          status: '1',
          show_counts: 1,
          action_conuts: 84,
          external_get: 8,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 213206,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '洛龙区',
          city: '洛阳市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/5ZJ2bk4QpgaRHyxWSKDhuZ5GiboQZH68TYBF68FIuib2ibUMcA3Pgt2Yp3KKa3PdOlVI1c55G3veicHwj1onDZ9ZVA/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6gI_cnl8CbhilFeYaVzwhOQ.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6gI_cnl8CbhilFeYaVzwhOQ.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '斯人若彩虹，遇上方知有。你好啊…！',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6gI_cnl8CbhilFeYaVzwhOQ.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '建筑行业',
          house: '无房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '50kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '一年内结婚',
          create_time: 1644578162,
          update_time: null,
          rec_time: 1645194262,
          birthday: '1991-09-20',
          work_data: '河南省,洛阳市,洛龙区',
          height: '158cm',
          income: '3K-5K',
          education: '本科',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,新乡市,封丘县',
          age: 30,
          tousu: 0,
          realname: '李楠',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 35,
          mincouple_age: 30,
          couple_marriage: '未婚',
          status: '1',
          show_counts: 2,
          action_conuts: 58,
          external_get: 4,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 210993,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '郑东新区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83ergNK1vI32HjkCEONxD6fCTUulyu3SGj5KkXswRibe8sbZD2eiaQwp6ia9lxgpITVX1TvUPuCd16vtag/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6rP8GNDhwqX7Z5El6aFF76o.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6rP8GNDhwqX7Z5El6aFF76o.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '比起心动 我更喜欢心安',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6rP8GNDhwqX7Z5El6aFF76o.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '财务',
          house: '有房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '55kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '两年内结婚',
          create_time: 1636022545,
          update_time: null,
          rec_time: 1645144714,
          birthday: '2000-03-28',
          work_data: '河南省,郑州市,郑东新区',
          height: '167cm',
          income: '5K-8K',
          education: '大专',
          marriage: '未婚',
          have_child: null,
          born_data: '河南省,郑州市,金水区',
          age: 22,
          tousu: 0,
          realname: '冯燕',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 26,
          mincouple_age: 22,
          couple_marriage: '未婚',
          status: '1',
          show_counts: 1,
          action_conuts: 118,
          external_get: 5,
          today_getwx: 0,
          all_getwx: 0,
        },
        {
          id: 213274,
          unionid: '',
          nickname: '',
          sex: '女',
          language: '',
          area: '金水区',
          city: '郑州市',
          province: '河南省',
          country: '',
          headimgurl:
            'https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eod2ZNIY8WNDbmChXBySAS6SYLajpVMjBKFN7GQ4koUehqEbOgiazoELFgJNibylAO3TJZrjHaocOTQ/132',
          upper:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/upper_oVyGO6vMv4sPFDPZ7HyliEECV5mY.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          body: 'http://oss.yijiehunlian.com/upload_zz/uploads/base/body_oVyGO6vMv4sPFDPZ7HyliEECV5mY.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          monologue: '',
          avatar:
            'http://oss.yijiehunlian.com/upload_zz/uploads/base/avatar_oVyGO6vMv4sPFDPZ7HyliEECV5mY.jpg?x-oss-process=image/resize,m_fill,h_200,w_200',
          complaint_num: null,
          deleted: 0,
          recommend: 1,
          subscribe: 0,
          want_child: null,
          profession: '职业职员',
          house: '无房-无车',
          car: null,
          born_province: '',
          born_city: '',
          born_area: '',
          weight: '43kg',
          bodily: null,
          smoke: '不抽烟不喝酒',
          drink: null,
          constellation: null,
          nation: '汉族',
          marry_date: '两年内结婚',
          create_time: 1645149331,
          update_time: null,
          rec_time: 1645144455,
          birthday: '1990-02-17',
          work_data: '河南省,郑州市,金水区',
          height: '156cm',
          income: '3K-5K',
          education: '本科',
          marriage: '离异',
          have_child: null,
          born_data: '河南省,焦作市,武陟县',
          age: 32,
          tousu: 0,
          realname: '郭女士',
          mobile: null,
          uname: null,
          vip_start: null,
          vip_end: null,
          vip: null,
          maxcouple_age: 55,
          mincouple_age: 18,
          couple_marriage: null,
          status: '1',
          show_counts: 2,
          action_conuts: 106,
          external_get: 2,
          today_getwx: 0,
          all_getwx: 0,
        },
      ],
    }
  },
  mounted() {
    setRem()
  },
  methods: {
    onLoad() {
      console.log(325)
    },
    handleClick(value) {
      this.$router.push('/home/detail')
    },
  },
}
</script>
<style lang="less" scoped>
.m-r-20 {
  margin-right: 20px;
}
.m-t-20 {
  margin-top: 20px;
}
.main {
  line-height: 30px;
}
</style>